name: Validate and Test

on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON files
        run: |
          npm install -g ajv-cli
          find data/database -name "*.json" -exec ajv validate -s data/schemas/item-schema.json -d {} \;
      
      - name: Check JSON formatting
        run: |
          npm install -g prettier
          prettier --check "data/**/*.json"
  
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
